FROM rocker/r-ver:4.1.0
#ALTERNATE:
#FROM rocker/shiny:latest
RUN apt-get update && \
    apt-get install -y git-core \
          imagemagick \
          libcairo2-dev \
          libcurl4-openssl-dev \
          libgit2-dev \
          libicu-dev \
          libmagic-dev \
          libmagick++-dev \
          libpng-dev \
          libssl-dev \
          libxml2-dev \
          make \
          pandoc \
          pandoc-citeproc \
          python zlib1g-dev \
          wget && \
          rm -rf /var/lib/apt/lists/*

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

## Docker inheritance
#FROM bioconductor/bioconductor_docker:devel
#
#RUN apt-get update
#    RUN R -e 'BiocManager::install(ask = F)' && R -e 'BiocManager::install(c("SingleCellExperiment", "LoomExperiment ask = F))'
## install renv & restore packages

ENV RENV_VERSION 0.14.0

RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'

#RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@${RENV_VERSION}')"

WORKDIR /omicser
COPY renv.lock renv.lock
RUN R -e 'renv::restore()'


#RUN mkdir /build_zone
#ADD . /build_zone
#WORKDIR /build_zone
WORKDIR /omicser
COPY . .
RUN R -e 'remotes::install_local(upgrade="never")'

#RUN rm -rf /build_zone #leave the source code...
#also need to run the reticulate functions...
EXPOSE 80
CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');omicser::run_app()"


# RUN mkdir /build_zone
# ADD . /build_zone
# WORKDIR /build_zone
# RUN R -e 'remotes::install_local(upgrade="never")'
# RUN rm -rf /build_zone
# EXPOSE 80
# CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');omicser::run_app()"


