---
title: "0-Overview and Quickstart"
date: "11/26/2021"
output:
  html_document: 
    toc: yes
    keep_md: yes
  md_document:
    variant: gfm
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

If you would like an overview of the features and functionality of the browser,
please view the [Browsing vignette](browsing.md).

The following vignettes are intended to guide curators through the process of creating a web application and formatting data for visualization in the browser.
The main vignettes in the series include:

1. [Installation](01_installation.md): install required R packages, dependencies and configuration of the nescessary Python environments
2. [Data curation](02_data_curation.md): pre-process, filter, and format -omics data
3. [Configuration](03_configuration.md): connect the database(s) with the application
4. [Launching and sharing](04_sharing.md): prepare the browser for sharing with collaborators

An additional vignette on [Adding multiple databases](multiple_databases.md) is also available.

Please view the [`examples/` directory of the GitHub repository](https://github.com/ndcn/omicser/tree/main/examples)
for this project to view files and scripts for a variety of use cases.

A short [installation & configuration tutorial video](https://www.youtube.com/watch?v=lwJmsxk0vTU) is also available which roughly follows this sequence of vignettes: 
