---
title: "4-Database Configuration"
author: "andy henrie"
date: "9/14/2021"
output:
  html_document: 
    keep_md: yes
    toc: true
  md_document:
    variant: gfm
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, setup-1, eval=FALSE}

# Now move to the directory where you want to execute the omicser
# and make the omicser_options.yml

OMICSER_RUN_DIR <- "full/path/to/where/omicser_options.yml/goes"

db_root_path <- "full/path/to/folder/where/DATABASES/go"

database_names <- list(
  "hello database" = "hello_database"
)

conda_environment = 'omxr'
omicser_options <- list(database_names=database_names,
                        db_root_path=db_root_path,
                        conda_environment=conda_environment)

omicser::write_config(omicser_options,in_path = OMICSER_RUN_DIR )

```

# WORK IN PROGRESS:  NOT written


``` {r, 3-config-1, eval=FALSE}
#==== 7. create configs =========================================================================
# differentials  #if we care we need to explicitly state. defaults will be the order...
conf_list <- list(
  x_obs = c("Is.Reference","Condition","Replicate", "Label"),
  y_obs =  c("expr_var", "expr_mean", "expr_frac", "sample_ID", "leiden"), #MEASURES
  obs_groupby = c("Is.Reference","Condition","Replicate", "Label"),
  obs_subset = c("Is.Reference","Condition","Replicate", "Label"),

  x_var = character(0),
  y_var = c("expr_geomean", "expr_mean", "expr_var", "expr_frac" ),

  var_groupby = character(0),
  var_subset = character(0),

  diffs = list(diff_exp_comps = levels(factor(diff_exp$versus)),
               diff_exp_comp_type =  levels(factor(diff_exp$comp_type)),
               diff_exp_obs_name =  levels(factor(diff_exp$obs_name)),
               diff_exp_tests =  levels(factor(diff_exp$test_type))
  ),

  layers = c("X","raw","X_is_scaled_na_to_0","scaled","zro_na"),

  # Dimred
  dimreds = list(obsm = ad$obsm_keys(),
                 varm = ad$varm_keys()),

  # what ad$obs do we want to make default values for...
  # # should just pack according to UI?
  default_factors = c("Condition","Color","Replicate")

)
configr::write.config(config.dat = conf_list, file.path = file.path(DS_ROOT_PATH,DB_NAME,"config.yml" ),
                      write.type = "yaml", indent = 4)


```



