---
title: "Adding multiple datasets"
output:
  html_document: 
    keep_md: yes
    toc: true
  md_document:
    variant: gfm
---

It is possible to visualize multiple datasets in the same initialized browser.
These datasets do not necessarily need to be from related projects.

The following sections summarize steps required to curate and visualize additional datasets,
with the assumption you have a browser that can be successfully launched to visualize a single dataset.

## Data curation

Each dataset will need to be curated individually,
which choices for processing and filtering dependent on the type of data involved.
All resulting database files should be located in the database folder,
with files for each database placed in a subdirectory with the dataset name.

## Configuration 

You will need a separate configuration file for each database,
also located in the database subdirectory for the relevant dataset.

Your original browser configuration file for visualizing a single database should be modified to include all additional databases.

If you have modified `additional_info.Rmd` to describe your data analysis methods,
you should add information about each additional dataset there as well.

## Browsing

Once the browser is launched,
the `Ingest` tab should now show all available databases in the drop-down menu.
