---
title: "Anndata objects"
output:
  html_document: 
    keep_md: yes
    toc: true
  md_document:
    variant: gfm
---

We have seeral tools that provide wrappers for convertign the anndata objects.  They all use reticulate.

package(anndata) or "anndata in R" is a really nice wrapper...

we can also load scanpy and anndata python modules with reticulate.

sc <- import("scanpy")
anndat <- import("anndata")


```{r, eval = FALSE}
require("Seurat")
require("sceasy")

require(reticulate)
reticulate::use_condaenv(required = TRUE, condaenv = 'omxr')
require(anndata)

DB_NAME = "vilas_microglia_sceasy"
DB_DIR = file.path("data-raw",DB_NAME)


RAW_DIR <- "ingest/Vilas_B"

microglia_data_updated <- readRDS(file = file.path(RAW_DIR, "microglia_data_seu_new.rds"))


ad <- sceasy::convertFormat(microglia_data_updated, from="seurat", to="anndata",
                      outFile = NULL,
                      assay = 'SCT',
                      main_layer = 'data',
                      transfer_layers = c('data', 'counts', 'scale.data')
                      )

raw <- sceasy::convertFormat(microglia_data_updated, from="seurat", to="anndata",
                            outFile = NULL,
                            assay = 'RNA',
                            main_layer = 'counts',
                            transfer_layers = NULL)


ad$raw <- raw


ad$write_h5ad(filename=file.path(DB_DIR,"core_data.h5ad"))

# confirm that casting to anndatainR wrapper doesn't change the file....
ad_R <- py_to_r(ad)
ad_R$write_h5ad(filename=file.path(DB_DIR,"core_dataR.h5ad"))

ad_py <- read_h5ad(file.path(DB_DIR,"core_data.h5ad"))
ad_R <- read_h5ad(file.path(DB_DIR,"core_dataR.h5ad"))



sc <- import("scanpy")
anndat <- import("anndata")


# R TOOLS
ad_r <- reticulate::py_to_r(ad)

var_ <- ad_r$var
obs <- ad_r$obs
X <- ad_r$X
ad_raw <- ad_r$raw
obsm <- ad_r$obsm
varm <- ad_r$varm

layers <- ad_r$layers$get('counts')

# db_prefix = "core_data"
# saveRDS(X, file = paste0(DB_DIR, "/", db_prefix, "_X.rds"))
# saveRDS(obs, file = paste0(DB_DIR, "/", db_prefix, "_obs.rds"))
# saveRDS(var_, file = paste0(DB_DIR, "/", db_prefix, "_var.rds"))

ad_ <- AnnData(
  X = X,
  obs = obs,
  var = var_,
  raw = ad_raw,
  obsm = obsm,
  varm=varm,
  layers =  list(counts=ad$layers$get('counts')) #list('count'=layers)
)

ad_

ad_$write_h5ad(filename=file.path(DB_DIR,"recastR.h5ad"))


detach("package:anndata",unload=TRUE)
sc <- import("scanpy")
anndat <- import("anndata")

var_ <- ad$var
obs <- ad$obs
X <- ad$X
ad_raw <- ad$raw
obsm <- ad$obsm
varm <- ad$varm

layers <- ad$layers


ad_py <- sc$AnnData(
  X = X,
  obs = obs,
  var = var_,
  raw = ad_raw,
  obsm = obsm,
  varm=varm,
  layers =  layers
)
#ad$write_h5ad(filename=file.path(DB_DIR,"core_data.h5ad"))
# returns AnnDataR6 !?!?!?

ad_py
ad_py$write_h5ad(filename=file.path(DB_DIR,"recast_py.h5ad"))


ad_py2 <- anndat$AnnData(
  X = ad$X,
  obs = ad$obs,
  var = ad$var,
  raw = ad$raw,
  obsm = ad$obsm,
  varm= ad$varm,
  raw = ad$raw,
  layers =  ad$layers
)
#ad$write_h5ad(filename=file
#
ad_py2$write_h5ad(filename=file.path(DB_DIR,"recast_py2.h5ad"))






```


We will add to this as we go along... for nwo we'll use teh anndata in R objects since we won't have to call reticulate::py_to_r() to exptract the bits from within the shiny app.




Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

