---
title: "Side-bar Info"
output: html_document
---
## Instructions

### 1. Load the database 
* In the `Ingest` tab - choose database
* choose the data columns to browse
* CLICK `Load Data`

### 2. Consider the Context
* spend a minute reading the _Database Information_ curated along with the database which renders on the right
* read the `Welcome` tab message

  
### 3. Select variables for visualization
* Using the selector on the left sidebar you can choose what variables and measures you would like to visualize.  
  * e.g. choosing a bunch of "target" *-omic features 
* CLICK `Plot Now!` to activate the selections in the playground

### 4. Play and Explore

* There are a variety of plots in the `Playground`
  - `Expression` tab 
    * heatmaps for visualizing the expression measures for chosen features
  - `Diff. Expr.` tab 
    * volcano plots of differential expression 
    * interactive auxuillary distributions and meta 
  - `Table` tab
    * browse -omic features via a data-table
* `Data Table` tab
  - allows for browsing the details of the data

* `Help` tab (WIP)
  - links to documentation, github repo, and more

  
  
© 2021 DataTecnica, Inc., CZI, NDCN, 

